services:
  qdd-gui:
    build: .
    ports:
      - "6080:6080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6080/vnc.html"]
      interval: 30s
      timeout: 5s
      retries: 3