# binder/environment.yml

name: tutorial-env
channels:
  - conda-forge # A good default channel for many packages
dependencies:
  # --- Core Python and Jupyter ---
  - python=3.9    # Choose a version compatible with your tools. Python 3.9 or 3.10 are good choices.
  - pip
  - jupyterlab    # Or jupyter-notebook if you prefer
  - ipykernel     # To ensure the Jupyter kernel uses this environment

  # --- Dependencies for SQDMetal ---
  # Add Metal /  SQDMetal's Python dependencies here. 
  - addict==2.4.0
  - descartes==1.1.0
  - geopandas==0.12.2
  - ipython==8.10.0
  - matplotlib==3.7.0
  - numpy==1.24.2
  - pandas==1.5.3
  - pint==0.20.1
  - pyepr-quantum==0.8.5.7
  - pygments==2.14.0
  - pyside2==5.15.8
  - qdarkstyle==3.1
  - qutip==4.7.1
  - gdspy==1.6.12
  - gdstk==0.9.60
  - scipy==1.10.0
  - shapely==2.0.1
  - scqubits==3.1.0
  - pyyaml==6.0
  - cython<3.0.0
  - gdspy==1.6.12
  - ipympl

  # --- Other Python packages from your script ---
  - pip:
    - pyvirtualdisplay
    - libceed
    - pyaedt==0.6.46
    - gmsh==4.11.1